Add -l to tmux-session

diff --git a/bin/tmux-session b/bin/tmux-session
--- a/bin/tmux-session
+++ b/bin/tmux-session
@@ -38,29 +38,59 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 
-TMUX_SESSION_LOOP=0
 set -euf -o pipefail
 
-TMUX_SESSION_NAME=0
-if [[ $# -gt 0 ]]; then
-  TMUX_SESSION_NAME="$1"
-fi
+TMUX_SESSION_LOOP=0
+TMUX_SESSION_NAME=""
+
+show_usage() {
+  echo "Usage: $0 [-h]" >&2
+  echo
+  echo "-h    Show this help message and exit"
+  echo "-l    Restart the tmux session after it quits"
+  exit 1
+}
+
+while getopts ":hl" opt; do
+  case ${opt} in
+  l)
+    TMUX_SESSION_LOOP=1
+    ;;
+  h)
+    show_usage
+    ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  :)
+    echo "Invalid option: -$OPTARG requires an argument" >&2
+    exit 1
+    ;;
+  esac
+done
+shift $((OPTIND - 1))
 
 open-tmux-session() {
   if ! tmux -2 attach-session -t "$TMUX_SESSION_NAME"; then
-    if tmux -2 new -s "$TMUX_SESSION_NAME"; then
-      exit 0
-    fi
-
-    exit 1
+    tmux -2 new -s "$TMUX_SESSION_NAME"
   fi
 }
 
-if [[ $TMUX_SESSION_LOOP ]]; then
-  while true; do
+main() {
+  if [[ $# -gt 0 ]]; then
+    TMUX_SESSION_NAME="$1"
+  fi
+
+  if [[ $TMUX_SESSION_LOOP -ne 0 ]]; then
+    while true; do
+      open-tmux-session
+      echo "Restarting the Tmux session '$TMUX_SESSION_NAME'..."
+      sleep 1
+    done
+  else
     open-tmux-session
-    sleep 1
-  done
-else
-  open-tmux-session
-fi
+  fi
+}
+
+main "$@"
