Improve allfiles and path-is

diff --git a/allfiles b/allfiles
--- a/allfiles
+++ b/allfiles
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Requirements: rg (ripgrep)
+# Requirements: rg (ripgrep) or fd or grep
 # Author: James Cherti
 # URL: https://github.com/jamescherti/bash-stdops
 #
@@ -37,8 +37,8 @@ set -euf -o pipefail
 if [[ $# -ne 1 ]]; then
   echo "Recursively search the specified directory and print the list of file "
   echo "paths."
-  echo "(By default, it ignores '.git' directories, files matching "
-  echo "'.gitignore' rules. When rg is used, it also ignores binary files.)"
+  echo "(By default, it ignores '.git' and '.svn' directories, files matching "
+  echo "'.gitignore' rules, and binary files.)"
   echo
   echo "Usage: $0 <dir>" >&2
   echo
@@ -51,21 +51,48 @@ if ! [[ -d "$DIR" ]]; then
   exit 1
 fi
 
-if type -P rg &>/dev/null; then
-  RG_CMD=(rg --hidden --no-messages --color=never --no-heading --files)
-  RG_CMD+=(--glob '!.git')
-  RG_CMD+=(--glob '!.svn')
-  RG_CMD+=("--" "$DIR")
-  exec "${RG_CMD[@]}"
-elif type -P fd &>/dev/null; then
-  # TODO: add filter for binary files
-  RG_CMD=(fd --hidden --color=never)
-  exec "${RG_CMD[@]}"
-elif type -P grep &>/dev/null; then
-  # TODO: add filter for binary files
-  RG_CMD=(grep --color=auto --exclude-dir=.git --exclude-dir=.svn)
-  exec "${RG_CMD[@]}"
-else
-  echo "Error: One of the following commands is required: rg, fd, or grep" >&2
+LIST_METHODS=(rg fd git find)
+
+METHOD_EXECUTED=""
+for METHOD in "${LIST_METHODS[@]}"; do
+  if [[ $METHOD = "rg" ]] && type -P rg &>/dev/null; then
+    METHOD_EXECUTED="rg"
+    RG_CMD=(rg --hidden --no-messages --color=never --no-heading --files
+      --no-ignore)
+    RG_CMD+=(--glob '!.git')
+    RG_CMD+=(--glob '!.svn')
+    RG_CMD+=("--" "$DIR")
+    "${RG_CMD[@]}"
+    break
+  elif [[ $METHOD = "fd" ]] && type -P fd &>/dev/null; then
+    METHOD_EXECUTED="fd"
+    RG_CMD=(fd --type f --hidden --color=never . "$DIR" --no-ignore)
+    "${RG_CMD[@]}" | qparallel path-is -sp '{}' text
+    break
+  elif [[ $METHOD = "git" ]] && type -P git &>/dev/null \
+    && git -C . rev-parse --is-inside-work-tree; then
+    METHOD_EXECUTED="git"
+    git ls-files "$DIR" | qparallel path-is -sp '{}' text
+    break
+  elif [[ $METHOD = "find" ]] && type -P find &>/dev/null; then
+    METHOD_EXECUTED="find"
+    RG_CMD=(find)
+    RG_CMD+=("$DIR")
+    RG_CMD+=(-type f)
+    RG_CMD+=(-a)
+    RG_CMD+=(-not -iwholename '*/.svn/*')
+    RG_CMD+=("-a")
+    RG_CMD+=(-not -iwholename '*/.git/*')
+    RG_CMD+=(-prune)
+    RG_CMD+=(-print)
+    "${RG_CMD[@]}" | qparallel path-is -sp '{}' text
+    break
+  fi
+done
+
+if [[ $METHOD_EXECUTED = "" ]]; then
+  echo "Error: One of the following commands is required: rg, fd, or find" >&2
   exit 1
+# else
+#   echo "[INFO] Successfully executed: $METHOD_EXECUTED" >&2
 fi
diff --git a/path-is b/path-is
--- a/path-is
+++ b/path-is
@@ -36,6 +36,46 @@
 
 set -euf -o pipefail
 
+show_usage() {
+  {
+    echo "Check whether a given file path points to a " \
+      "binary file or a text file."
+    echo ""
+    echo "Usage: $0 [-h] <path/to/existing/file> <binary|text>"
+    echo
+    echo "-h    Show this help message and exit"
+    echo "-s    Always exit with a status of 0"
+    echo "-p    Print the path when it correspond to the specified type"
+  } >&2
+}
+
+NEVER_FAIL=0
+PRINT_PATH=0
+while getopts ":hsp" opt; do
+  case ${opt} in
+  p)
+    PRINT_PATH=1
+    ;;
+  s)
+    NEVER_FAIL=1
+    ;;
+  h)
+    show_usage
+    exit 1
+    ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  :)
+    echo "Invalid option: -$OPTARG requires an argument" >&2
+    exit 1
+    ;;
+  esac
+done
+
+shift $((OPTIND - 1))
+
 _is_binary() {
   # Grep options:
   # -------------
@@ -49,18 +89,20 @@ _is_binary() {
 }
 
 if [[ $# -lt 2 ]]; then
-  echo "Check whether a given file path points to a " \
-    "binary file or a text file." >&2
-  echo "" >&2
-  echo "Usage: $0 <path/to/existing/file> <binary|text>" >&2
+  show_usage
   exit 1
 fi
 
 PATH_EXISTING_FILE="$1"
 shift
 
-if ! [[ -f "$PATH_EXISTING_FILE" ]]; then
+if ! [[ -e "$PATH_EXISTING_FILE" ]]; then
   echo "Error: No such file or directory: $PATH_EXISTING_FILE" >&2
+  exit 1
+fi
+
+if ! [[ -f "$PATH_EXISTING_FILE" ]]; then
+  echo "Error: The following path is not a file: $PATH_EXISTING_FILE" >&2
   exit 1
 fi
 
@@ -71,9 +113,17 @@ for REQUEST in "$@"; do
     continue
   fi
 
-  printf "Error: The following path is not '%s': %s\n" \
-    "$REQUEST" "$PATH_EXISTING_FILE"
-  exit 1
+  if [[ $NEVER_FAIL -ne 0 ]]; then
+    exit 0
+  else
+    printf "Error: The following path is not '%s': %s\n" \
+      "$REQUEST" "$PATH_EXISTING_FILE"
+    exit 1
+  fi
 done
 
-printf "%s\n" "$PATH_EXISTING_FILE"
+if [[ $PRINT_PATH -ne 0 ]]; then
+  printf "%s\n" "$PATH_EXISTING_FILE"
+fi
+
+exit 0
